### ISSUE TITLE
Cannot use `Duration::toLocaleString`

### ISSUE THREAD

**Issue by Crisfole** [fullcalendar/temporal-polyfill#24]
I'd like to opt into using your Duration.toLocaleString formatting; knowing the dangers of using an API that's not stage 4. I don't see a more recent implementation of `durationformat-polyfill` and adding a _separate_ DurationFormat polyfill to `Intl` does not seem to help.

[The proposal](https://tc39.es/proposal-temporal/docs/duration.html#toLocaleString) says that:

> If Intl.DurationFormat is not available, then the output of this method is the same as that of duration.toString(), and the locales and options arguments are ignored.

So I expected the polyfill to check for a polyfilled `Intl.DurationFormat`, but it did not.

**Comment by arshaw** [comment]
Hi @Crisfole , this should have been working [since v0.2.0](https://github.com/fullcalendar/temporal-polyfill/blob/v0.2.0/packages/temporal-polyfill/src/classApi/duration.ts#L76) and it's definitely working now [with version 0.2.0](https://github.com/fullcalendar/temporal-polyfill/blob/v0.2.1/packages/temporal-polyfill/src/classApi/duration.ts#L146-L148), which now correctly falls back to `toString` if `Intl.DurationFormat` is not available.

Could you give it another try with the latest version of temporal-polyfill and report back? I want to be sure the DurationFormat polyfill you chose is not the issue.

**Comment by Crisfole** [comment]
I can verify the updated temporal-polyfill works as expected! Thank you for the heads up!
