### ISSUE TITLE
RangeError: Missing relativeTo

### ISSUE THREAD

**Issue by steida** [fullcalendar/temporal-polyfill#29]
Is this code wrong?

```ts
const monthsSinceEpoch = value
  .since(Temporal.PlainDate.from("1970-01-01"))
  .total({ unit: "months" });
```

Another example:
```ts
const weeksSinceEpoch = Math.floor(
  getStartOfWeek(date)
    .toZonedDateTime(now.timeZoneId())
    .toInstant()
    .since(Temporal.Instant.fromEpochMilliseconds(0))
    // "weeks" throws `RangeError: Missing relativeTo` for some reason
    .total({ unit: "milliseconds" }) / millisecondsPerWeek,
);
```

Btw, thank you for the awesome lib!

**Comment by arshaw** [comment]
Hi @steida , that is part of the spec and is expected behavior... Temporal works with a number of different calendar systems (not just the Gregorian one that you and I are used to), so it requires a little more work. A `Duration` object on its own is not enough to know how many weeks/months total something is. You need to give it a reference point (aka "relativeTo"). Just give it the first date you have. Something like this:

```js
const epoch = Temporal.PlainDate.from("1970-01-01");
const value = Temporal.Now.plainDateISO();
const monthsSinceEpoch = value.since(epoch).total({ unit: 'months', relativeTo: epoch });
```

**Comment by arshaw** [comment]
If you'd like to round it to a whole-number right away, you can do this instead:

```js
const integerMonthsSinceEpoch = value.since(epoch, {
  largestUnit: 'month',
  smallestUnit: 'month'
}).months
```

**Comment by arshaw** [comment]
If the `getStartOfWeek` function always returns dates that are aligned to the start-of-week, then yes, the returned duration should only ever have a 'weeks' value.

Just curious, where is this `getStartOfWeek` function coming from?
