### ISSUE TITLE
PlainTime.toString() throws error on Next.js production builds

### ISSUE THREAD

**Issue by cbodin** [fullcalendar/temporal-polyfill#36]
Minimal reproducible example:
https://codesandbox.io/p/devbox/temporal-polyfill-nextjs-bug-7n38kr?file=%2Fapp%2Fpage.tsx

Running `npm run dev` works as expected, `npm run build-start` will throw an error when clicking the button.

**Comment by arshaw** [comment]
Thanks for the report @cbodin. After some frustrating debugging, I've found this is a minification bug in Next's SWC.

If you set `swcMinify: false` in your next.config.js, you'll see the problem goes away.

I need to further reduce where the problem is happening. In temporal-polyfill's sourcecode, somewhere near the array spread in `formatPlainTimeIso`.

**Comment by arshaw** [comment]
^^See above issue in swc

**Comment by arshaw** [comment]
Very soon after I reported this bug to SWC, they fixed it.

Also, I created an easy workaround for older versions of SWC/Next.js and released it in [v0.2.4](https://github.com/fullcalendar/temporal-polyfill/releases/tag/v0.2.4)
