### ISSUE TITLE
Converting a `PlainDateTime` to a `ZonedDateTime` with disambiguation `earlier` when wall clock is moved forwards

### ISSUE THREAD

**Issue by felixschorer** [fullcalendar/temporal-polyfill#45]
Hello,

there seems to be an issue when converting a `PlainDateTime` to a `ZonedDateTime` with disambiguation `earlier` when the clock is moved forwards (e.g. time change from winter to summer time).

```ts
// Wall clock is moved forwards by an hour on 2024-03-31 at 02:00 in Europe/Berlin time zone.
// CET (+01:00) -> CEST (+02:00)
const plain = Temporal.PlainDateTime.from("2024-03-31T02:00")

// ambiguous, either 2024-03-31T02:00:00+01:00 (CET) or 2024-03-31T03:00:00+02:00 (CEST)
const zoned = plain.toZonedDateTime("Europe/Berlin", { disambiguation: "earlier" })

expect(zoned.toString()).toBe("2024-03-31T02:00:00+01:00[Europe/Berlin]")
// actually 2024-03-31T01:00:00+01:00[Europe/Berlin], so an hour earlier in UTC
```

I am not sure if that's the expected result, but it seem unintuitive to me.

Kind regards,
Felix Schorer

**Comment by arshaw** [comment]
Hi @felixschorer. Here's why the results are the way they are:

- In the `Europe/Berlin` time zone, on `2024-03-31`, there's a nonexistent wallclock hour from 02:00 -> 02:59
- The PlainDate your provided (`2024-03-31T02:00`) has a wallclock time of `02:00`, which falls within this hour
- When toZonedDateTime is called with a non-`reject` disambiguation setting, it must return a ZonedDateTime
  - When `earlier`, the wallclock time of the result will end up being -1 hour than requested in order to push it in-bounds
  - When `later`, the wallclock time of the result will end up being +1 hour than requested in order to push it in-bounds

Your `earlier` setting causes the resulting ZonedDateTime have a wallclock time of `02:00 - 1 hour = 01:00`, which will have the timezone offset that the side BEFORE the transition has, which is +01:00. Thus, `2024-03-31T01:00:00+01:00[Europe/Berlin]` is correct

**Comment by felixschorer** [comment]
@arshaw Thank you for clearing up my misunderstanding. I apprechiate the detailed explanation.
